# Docker Compose file format version for reference and compatibility
# While not strictly required in newer versions, this helps with:
# - Documentation of intended Compose features
# - IDE support and syntax highlighting
# - Team collaboration and code review
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fireflies-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: firefliesuser
      POSTGRES_PASSWORD: firefliespass
      POSTGRES_DB: firefliesdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U firefliesuser -d firefliesdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: fireflies-adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra

  web:
    build: .
    container_name: fireflies-streamlit
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: firefliesuser
      DB_PASSWORD: firefliespass
      DB_NAME: firefliesdb
    ports:
      - "8501:8501"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: fireflies-nginx
    depends_on:
      - web
      - adminer
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  db_data: 